# -*- coding: utf-8 -*-
"""parse_securities.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ifpoOvcnuO7N29nFJIOW16z9euKegf3

## Install Libraries
"""

# !pip install PyMuPDF

"""## Set Paths"""

import re
import fitz
import pandas as pd

PDF_PATH = "/content/12868725710.pdf"
PDF_PATH = "/content/10253764130.pdf"
PDF_PATH = "/content/14831677350.pdf"

pattern = re.compile(
    r'(?P<Shares_Value>[\d,]+\.\d+)\s*'
    r'(?P<Available_Qty>[\d,]+)\s*'
    r'(?P<Price>[\d,]+\.\d+)\s*'
    r'(?P<Symbol>[A-Z0-9]+)\s*'
    r'(?P<UIN>\d{13})\s*'
    r'(?P<CDS_Account_No>\d+)\s*'
    r'(?P<Participant_ID>\d+)\s*'
    r'(?P<Inventory_Date>\d{2}/\d{2}/\d{4})'
)

doc = fitz.open(PDF_PATH)

rows = list()
for page in doc:
    blocks = page.get_text("blocks")
    for block in blocks:
        line = block[4]
        if len(line.split('\n')) == 9:
            matches = pattern.finditer(line)
            for match in matches:
                rows.append(match.groupdict())

df = pd.DataFrame(rows)

df

df["Shares_Value"] = df["Shares_Value"].str.replace(",", "").astype(float)
df["Available_Qty"] = df["Available_Qty"].str.replace(",", "").astype(int)
df["Price"] = df["Price"].str.replace(",", "").astype(float)
df["Inventory_Date"] = pd.to_datetime(df["Inventory_Date"], format="%d/%m/%Y")

df["UIN"] = df["UIN"].str.replace(",", "").astype(int)
df["CDS_Account_No"] = df["CDS_Account_No"].str.replace(",", "").astype(int)
df["Participant_ID"] = df["Participant_ID"].str.replace(",", "").astype(int)

df.to_csv("parsed_sale.csv", index=False)

result

df.columns

avg_price_per_symbol = df.groupby("Symbol", as_index=False).apply(
    lambda x: pd.Series({
        "Total_Shares": x["Available_Qty"].sum(),
        "Average_Price": x["Shares_Value"].sum() / x["Available_Qty"].sum()
    })
).reset_index(drop=True)

print(avg_price_per_symbol)

avg_price_per_symbol.to_csv("avg_price.csv", index=False)

df

avg_price_per_symbol

import pandas as pd

# Sample data
ground_truth_df = pd.read_csv("/content/investment_plan (6).csv")

current_df = avg_price_per_symbol

# Normalize column names
current_df = current_df.rename(columns={"Symbol": "SYMBOL", "Total_Shares": "SHARES_CURRENT"})

# Merge on SYMBOL
merged = pd.merge(ground_truth_df, current_df, on="SYMBOL", how="outer")

# Fill NaNs for missing symbols
merged["SHARES"].fillna(0, inplace=True)           # Ground truth missing => 0 target shares
merged["SHARES_CURRENT"].fillna(0, inplace=True)   # Currently missing => 0 current shares

# Calculate difference
merged["DIFF"] = merged["SHARES"] - merged["SHARES_CURRENT"]

# Determine action
def determine_action(diff):
    if diff > 0:
        return "BUY"
    elif diff < 0:
        return "SELL"
    else:
        return "HOLD"

merged["ACTION"] = merged["DIFF"].apply(determine_action)

# Optional: Absolute shares to buy/sell
merged["SHARES_TO_TRADE"] = merged["DIFF"].abs()

# Final result
result_df = merged[["SYMBOL", "SHARES_CURRENT", "SHARES", "SHARES_TO_TRADE", "ACTION"]]
print(result_df)

result_df.to_csv('plan_to_follow.csv')

# Normalize column names
current_df = current_df.rename(columns={"Symbol": "SYMBOL", "Total_Shares": "SHARES_CURRENT"})

# Merge on SYMBOL
merged = pd.merge(ground_truth_df, current_df, on="SYMBOL", how="outer")

# Fill NaNs for missing symbols
merged["SHARES"].fillna(0, inplace=True)           # Ground truth missing => 0 target shares
merged["SHARES_CURRENT"].fillna(0, inplace=True)   # Currently missing => 0 current shares
merged["CURRENT_PRICE"].fillna(0, inplace=True)    # Missing price => 0

# Calculate difference
merged["DIFF"] = merged["SHARES"] - merged["SHARES_CURRENT"]

# Determine action
def determine_action(diff):
    if diff > 0:
        return "BUY"
    elif diff < 0:
        return "SELL"
    else:
        return "HOLD"

merged["ACTION"] = merged["DIFF"].apply(determine_action)
merged["SHARES_TO_TRADE"] = merged["DIFF"].abs()

# Calculate total cost
def calc_total_cost(row):
    if row["ACTION"] == "BUY":
        return row["SHARES_TO_TRADE"] * row["CURRENT_PRICE"]
    elif row["ACTION"] == "SELL":
        return -row["SHARES_TO_TRADE"] * row["CURRENT_PRICE"]
    else:
        return 0

merged["TOTAL_COST"] = merged.apply(calc_total_cost, axis=1)

# Final plan
result_df = merged[["SYMBOL", "CURRENT_PRICE", "SHARES_CURRENT", "SHARES", "SHARES_TO_TRADE", "ACTION", "TOTAL_COST"]]
print(result_df)

result_df

lines_num = """9679.46
8277.12
7955.26
7152.09
5368.83
4041.54
3800
3710.33
3416.6
3235.26
3205.36
2772.48
2686.36
2531.5
2369.29
2178.85
1700.72
1275.6
1097.91
943.52
897.75
890.58
855.84
852.28
833.1
753.44
645.66
531.28
490.9
474.75
455.28
420.66
411.47
401.58
400.12
399.86
388.6
380.3
367.32
357.68
357.28
350.49
340.76
297.63
287.97
268.75
244.72
239.08
215.76
190.2
185.46
152.4
117.2
103.8
103.08
39.84
34"""

sum(map(float, lines_num.splitlines()))

